### ISSUE TITLE
I got an error from reading a InetSocketAddress...

### ISSUE THREAD

**Issue by Flonja** [CloudburstMC/Network#6]
Stacktrace: https://pastebin.com/xmE0axx3

**Comment by SupremeMortal** [comment]
Were you connecting to an official RakNet implementation or something else?

**Comment by Chqmpignon** [comment]
fr.hivebedrock.network

**Comment by SupremeMortal** [comment]
Going to close this since it's been inactive for a year and haven't come across this issue myself.
