### ISSUE TITLE
Prevent IP Fragmentation

### ISSUE THREAD

**Issue by SupremeMortal** [CloudburstMC/Network#8]
Java does not support disabling IP fragmentation with the `IP_DONTFRAG` socket option which causes some networks and VPNs consistently not being able to connect due to how Raknet discovers MTU.

JBS Issue: https://bugs.openjdk.java.net/browse/JDK-8238725

**Comment by bundabrg** [comment]
I think this is backwards. Java always sets the DF flag. In the following screenshot 172.16.20.118 is my geyser server and 172.16.20.107 is a bedrock client on an ios tablet.

![image](https://user-images.githubusercontent.com/1607029/89093244-16b5a600-d3eb-11ea-8faa-dfffe2fb00f1.png)

**Comment by bundabrg** [comment]
A tcpdump of BDS shows it always has DF set for server->client as well.

**Comment by SupremeMortal** [comment]
Maybe the default value set depends on the operating system? I'm going to say it's still an issue if it has been reported on the OpenJDK bug tracker.

**Comment by SupremeMortal** [comment]
Fixed by https://github.com/CloudburstMC/Network/commit/f231b1f82d1269da545e5ef34822978ac6b88fe7
Also fixed in OpenJDK 19+20 https://github.com/openjdk/jdk/commit/67755edd6ff2e2eeafafec207d0459bca53f882b
